### ISSUE TITLE
gulp-useref plugin not working

### ISSUE THREAD

**Issue by JeevanJames** [JeevanJames/angular-template#13]
**gulp-useref** plugin, used in the **optimize_build** task is throwing an error. Looks like the latest versions are not backward compatible.

_TypeError: $.useref.assets is not a function
    at Gulp.<anonymous> (D:\Code\angular-template\gulpfile.js:323:27)
    at module.exports (D:\Code\angular-template\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Code\angular-template\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Code\angular-template\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\Code\angular-template\node_modules\orchestrator\index.js:134:8)
    at runNextSet (D:\Code\angular-template\node_modules\run-sequence\index.js:88:16)
    at Gulp.onTaskEnd (D:\Code\angular-template\node_modules\run-sequence\index.js:77:5)
    at emitOne (events.js:95:20)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (D:\Code\angular-template\node_modules\orchestrator\index.js:264:8)_

**Comment by JeevanJames** [comment]
The plugin API has breaking changes in the latest version. This specific issue has been fixed, but now there is a new issue when used with gulp-rev.
Opening a new bug for this (#16).
